### ISSUE TITLE
PreparedStatement with currentTimestamp() function 

### ISSUE THREAD

**Issue by carl10086** [scylladb/java-driver#110]
1. schema 

```sql
CREATE TABLE user_piper(
       occur_day date,
       occur_at timestamp,
       meta_act tinyint,
       meta_id bigint,
       sender_id bigint,
       meta_at timestamp,
       msg text,
       primary key(occur_day, occur_at, meta_id , meta_act, sender_id))
       WITH CLUSTERING ORDER BY (occur_at DESC)
       AND default_time_to_live = 1209600
       AND COMPACTION = {
           'class': 'TimeWindowCompactionStrategy',
           'compaction_window_size': 1,
           'compaction_window_unit': 'DAYS'
        };
```

2. insert sql

```sql
INSERT INTO user_piper (occur_day,occur_at,meta_id,meta_act,sender_id,meta_at,msg) VALUES(currentDate(),currentTimestamp(), ?,?,?,?,?),
```

3. problems .

when i use PreparedStatement , the `currentTimestamp()` always the first time I prepared the sql . 

when i use SimpleStatement, it's completely fine .

4. question ?
It's any option to change the default behavior of PreparedStatement when handing the function like currentTimestamp()

**Comment by avelanarius** [comment]
This problem was fixed in Scylla (https://github.com/scylladb/scylla/commit/21d758020a878247fdd1f259f703ecec9483fb3e) - it should work correctly with Scylla 4.6 (4.6 rc0/rc1 are now released). For older versions of Scylla, a reasonable workaround would be to still use `PreparedStatement` but without `currentTimestamp()` and `currentDate()`:

```
INSERT INTO user_piper (occur_day,occur_at,meta_id,meta_act,sender_id,meta_at,msg) VALUES(?,?,?,?,?,?,?)
```

instead filling those two values client-side in `bind()` (should not be a huge overhead).

Refs https://github.com/scylladb/scylla/issues/8816.
