### ISSUE TITLE
[guardrails] Make driver warnings more apparent to users

### ISSUE THREAD

**Issue by ptrsmrn** [scylladb/java-driver#247]
Guardrails control if a certain Scylla parameter is "OK", and can issue a CQL warning if it's not. This warning has to be visible by users. Currently, drivers' users can query for a warning themselves via API (e.g. for java - https://java-driver.docs.scylladb.com/scylla-3.10.2.x/api/com/datastax/driver/core/ExecutionInfo.html#getWarnings--), but this may not be enough, and it's desirable to increase warnings visibility. One idea presented by @avelanarius to accomplish that is to utilize native logging lib of a given driver to log warnings. If we decide to go with logging, perhaps it'd be good to introduce some rate-limiting, as to not spam the logs unnecessarily. 
Additional comments:
1. Drivers throw an exception in case CQL fails, so in case guadrail's "fail" threshold is exceeded, an exception would be thrown, so we basically are covered with regards to this scenario.
2. This request was opened against the java driver, but concerns all our drivers. 
3. All drivers we support already provide an API to query for returned CQL warnings.
4. We can think of writing some tests that would validate if guardrail's warnings/errors are really handled by our drivers correctly and to assert this functionality doesn't degrade over time.

**Comment by avikivity** [comment]
Warnings should go by default to the log, but there should be a way to the application to disable logging (and retrieve warnings programmatically). cqlsh can do that for example.

**Comment by Bouncheck** [comment]
I've looked at java driver so far. In version 3.x logging server side warnings is enabled by default and everything is logged with "WARN" severity. This can be controlled by setting `com.datastax.driver.DISABLE_QUERY_WARNING_LOGS` system property to `true`.
In version 4.x it also is enabled by default, however it's controlled by setting `advanced.request.log-warnings` config to true/false. Likewise, every message is logged as a "WARN".

There are some tests for that functionality, but they are all disabled for Scylla because example query being used does not actually generate server-side warning with Scylla - only with Cassandra.

**Comment by Bouncheck** [comment]
It seems I forgot to type an update.
I've checked python-driver, scylla-rust-driver, cpp-driver too. As long as logging is enabled these warnings will be outputted with WARN severity and no additional work is needed to see them.
In gocql I'm not sure if there is a way to configure it so that if a query produces a server side warning it is automatically outputted to console, but the warning definitely can be accessed programmatically.

Should we close this issue here and if there is a need to extend this functionality in a particular driver we can open a new issue in its repo?

**Comment by ptrsmrn** [comment]
@Bouncheck Yeah, I think that closes the issue, thanks.

Just for future reference, scylla OSS master (and 5.4) already have RF guardrail in, so setting e.g. `minimum_replication_factor_warn_threshold` config option to `3` and creating a ks with RF < 3 should result in a driver-side warninig.
