### ISSUE TITLE
CI is running against Scylla 5.3.0-rc0?!

### ISSUE THREAD

**Issue by mykaul** [scylladb/java-driver#290]
I'm not sure why, but this is a completely outdated version. Please move to latest 5.4.x.

**Comment by roydahan** [comment]
Looks like the CI pulls all the relevant scylla tags from dockerhub by this script and parameters:
`python3 ci/version_fetch.py scylla-oss-stable:2 scylla-oss-rc scylla-enterprise-stable:2 scylla-enterprise-rc`
Which indeed returned: 
`["2023.1.7", "5.2.17", "2024.1.3", "5.4.6", "5.3.0-rc0"]`

As a first remediation, I removed the '5.3.0-rc0' tag from our dockerhub since there is no such version.
This case was a "special case" that the script couldn't handle since we skipped this version and didn't release it.

However, it brings me to the question, do we really want to run the CI with the parameter of fetching the OSS RC releases?

**Comment by roydahan** [comment]
This is the current result of the script after removing the 5.3.0-rc0 tag from dockerhub:

```
 python /Users/roy/Downloads/version_fetch.py scylla-oss-stable:2 scylla-oss-rc scylla-enterprise-stable:2 scylla-enterprise-rc
["2024.1.3", "5.4.6", "5.2.17", "2023.1.7"]
```

**Comment by avelanarius** [comment]
> However, it brings me to the question, do we really want to run the CI with the parameter of fetching the OSS RC releases?

The original rationale was to test the driver against pre-release Scylla versions to be able to catch some bugs earlier, but I admit that the java-driver-matrix probably is a better place to catch it, not this repo.

**Comment by roydahan** [comment]
Sent PR to ignore oss-rc in CI.
