### ISSUE TITLE
Driver shall not call System.out.println for logging

### ISSUE THREAD

**Issue by sitano** [scylladb/java-driver#32]
https://github.com/scylladb/java-driver/blame/4.8.0-scylla/core/src/main/java/com/datastax/oss/driver/api/core/session/SessionBuilder.java#L660

Driver shall not call System.out.println for logging:

```
  public CompletionStage<SessionT> buildAsync() {
    System.out.println("Using Scylla optimized driver!!!");
    LOG.info("Using Scylla optimized driver!!!");
```

introduced by https://github.com/scylladb/java-driver/commit/f621035784b955d62ce423a64164a35f14e5a1d2.

Reasoning
===

`System.out.println` is not a logger and can't be configured by the library user. LOG usage is enough.

**Comment by haaawk** [comment]
Won't fix.

**Comment by pveentjer** [comment]
Professional Java libraries should not use System.out. There is a logger here already, that should be sufficient.

The user can configure how the data is written to file. With a system.out, the user has no control and therefor considered a bad practice.

**Comment by haaawk** [comment]
This is not backward compatible change (some users may rely on this message being printed) and the log is once per application run so it's harmless.

**Comment by pveentjer** [comment]
Systems.out is not an accepted practice for professional Java libraries.

**Comment by haaawk** [comment]
I agree it was a mistake to use it but removing it just like that may cause someone to lose hours of investigation why their shard aware driver stopped working.

**Comment by haaawk** [comment]
What I can do is to guard this print with configuration flag that is on by default and allow user to disable the flag if the print is a problem but we didn't have a single user complaining so it's probably a theoretical problem.

**Comment by pveentjer** [comment]
A user will probably not make a ticket. But if you get a new phone and the pages of the user guide are completely stained, you will probably not return the phone. But it will leave you with a bad taste in your mouth.

And writing to System.out can lead to all kinds of weird behavior when there are multiple applications running e.g. application server. Normally you can guide the logging, but you end up with a weird message in the System.out you can't easily pinpoint to an application.

If people have logging problems, they should deal with that problem first. Otherwise all logging should be copied so that we get the guarantee everything is guaranteed to be logged.

**Comment by RadoBuransky** [comment]
Agree with @pveentjer. Fix this guys.

**Comment by jimmypouliot** [comment]
I would like to see this fixed as well. It pollutes our logs, especially our test logs where the statement appears several times because they get forked.

I'd be OK with the configuration flag idea.
